version: '3.5'

volumes:
  mysql_data:

services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/confd:/etc/nginx/conf.d
      - ./nginx/vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - ./common.conf:/etc/nginx/common.conf:ro

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    restart: always
    volumes:
      - ./nginx/confd:/etc/nginx/conf.d
      - ./nginx/vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.tmpl.conf:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: '-notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf'

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx
    volumes:
      - ./nginx/confd:/etc/nginx/conf.d
      - ./nginx/vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: '--character-set-server=utf8 --collation-server=utf8_unicode_ci'
    env_file:
      - mysql.env

  dev-api:
    image: openlab.ncl.ac.uk:4567/gabber/api:1.0.4
    restart: unless-stopped
    container_name: dev-api
    environment:
      WEB_HOST: https://dev.gabber.audio
      VIRTUAL_HOST: api.dev.gabber.audio
      LETSENCRYPT_HOST: api.dev.gabber.audio
      LETSENCRYPT_EMAIL: gabber@jawrainey.me
    env_file: gabber-dev.env
    links:
      - mysql

  dev-web:
    image: openlab.ncl.ac.uk:4567/gabber/web:1.0.0-beta.11
    restart: unless-stopped
    container_name: dev-web
    environment:
      CONFIG_KEYS: API_URL
      API_URL: https://api.dev.gabber.audio/api
      VIRTUAL_HOST: dev.gabber.audio
      LETSENCRYPT_HOST: dev.gabber.audio
      LETSENCRYPT_EMAIL: gabber@jawrainey.me

  ifrc-api:
    image: openlab.ncl.ac.uk:4567/gabber/api:1.0.4
    restart: unless-stopped
    container_name: ifrc-api
    environment:
      WEB_HOST: https://ifrc.gabber.audio
      VIRTUAL_HOST: api.ifrc.gabber.audio
      LETSENCRYPT_HOST: api.ifrc.gabber.audio
      LETSENCRYPT_EMAIL: gabber@jawrainey.me
    env_file: gabber-ifrc.env
    links:
      - mysql

  ifrc-web:
    image: openlab.ncl.ac.uk:4567/gabber/web:1.0.0-beta.11
    restart: unless-stopped
    container_name: ifrc-web
    environment:
      CONFIG_KEYS: API_URL
      API_URL: https://api.ifrc.gabber.audio/api
      VIRTUAL_HOST: ifrc.gabber.audio
      LETSENCRYPT_HOST: ifrc.gabber.audio
      LETSENCRYPT_EMAIL: gabber@jawrainey.me
