version: '3.5'

volumes:
  mysql_data:

services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/confd:/etc/nginx/conf.d
      - ./nginx/vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - ./redirs.conf:/etc/nginx/conf.d/redirs.conf
      - ./common.conf:/etc/nginx/common.conf:ro

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    restart: always
    volumes:
      - ./nginx/confd:/etc/nginx/conf.d
      - ./nginx/vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.tmpl.conf:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: '-notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf'

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx
    volumes:
      - ./nginx/confd:/etc/nginx/conf.d
      - ./nginx/vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: '--character-set-server=utf8 --collation-server=utf8_unicode_ci'
    env_file:
      - mysql.env

  main-api:
    image: gabber/api:0.0.7-beta
    restart: unless-stopped
    container_name: main-api
    environment:
      WEB_HOST: https://gabber.audio
      VIRTUAL_HOST: api.gabber.audio
      LETSENCRYPT_HOST: api.gabber.audio
      LETSENCRYPT_EMAIL: gabber@jawrainey.me
    env_file: gabber-main.env
    links:
      - mysql

  main-web:
    image: openlab.ncl.ac.uk:4567/gabber/web:1.0.0-beta.23
    restart: unless-stopped
    container_name: main-web
    environment:
      CONFIG_KEYS: API_URL, ANALYTICS_ID, ANDROID_URL, IOS_APP_ID, IOS_URL
      API_URL: https://api.gabber.audio/api
      ANALYTICS_ID: UA-31608066-2
      ANDROID_URL: uk.ac.ncl.openlab.gabber
      IOS_APP_ID: 1356509623
      IOS_URL: gabber/id1356509623
      VIRTUAL_HOST: gabber.audio
      LETSENCRYPT_HOST: gabber.audio
      LETSENCRYPT_EMAIL: gabber@jawrainey.me

  dev-api:
    image: gabber/api:0.0.9-beta
    restart: unless-stopped
    container_name: dev-api
    environment:
      WEB_HOST: https://dev.gabber.audio
      VIRTUAL_HOST: api.dev.gabber.audio
      LETSENCRYPT_HOST: api.dev.gabber.audio
      LETSENCRYPT_EMAIL: gabber@jawrainey.me
    env_file: gabber-dev.env
    links:
      - mysql

  dev-web:
    image: openlab.ncl.ac.uk:4567/gabber/web:1.0.0-beta.24
    restart: unless-stopped
    container_name: dev-web
    environment:
      CONFIG_KEYS: API_URL, ANALYTICS_ID, ANDROID_URL, DEV_MODE, IOS_APP_ID, IOS_URL
      API_URL: https://api.dev.gabber.audio/api
      ANALYTICS_ID: UA-31608066-2
      ANDROID_URL: uk.ac.ncl.openlab.dev.gabber
      DEV_MODE: 'true'
      IOS_APP_ID: 1356509623
      IOS_URL: gabber/id1356509623
      VIRTUAL_HOST: dev.gabber.audio
      LETSENCRYPT_HOST: dev.gabber.audio
      LETSENCRYPT_EMAIL: gabber@jawrainey.me

  talk-futures-api:
    image: gabber/api:0.0.9-beta
    restart: unless-stopped
    container_name: talk-futures-api
    environment:
      WEB_HOST: https://talk.future-rcrc.com
      VIRTUAL_HOST: api.future-rcrc.com
      LETSENCRYPT_HOST: api.future-rcrc.com
      LETSENCRYPT_EMAIL: talk@future-rcrc.com
    env_file: talk-futures.env
    links:
      - mysql

  talk-futures-web:
    image: gabber/web:tf-0.0.11-b
    restart: unless-stopped
    container_name: talk-futures-web
    environment:
      CONFIG_KEYS: API_URL, ANALYTICS_ID, ANDROID_URL, COMING_SOON, IOS_APP_ID, IOS_URL
      API_URL: https://api.future-rcrc.com/api
      ANALYTICS_ID: UA-125029120-1
      ANDROID_URL: uk.ac.ncl.openlab.ifrc.gabber
      COMING_SOON: 'true'
      IOS_APP_ID: 1387310844
      IOS_URL: gabber-ifrc/id1387310844
      VIRTUAL_HOST: talk.future-rcrc.com
      LETSENCRYPT_HOST: talk.future-rcrc.com
      LETSENCRYPT_EMAIL: talk@future-rcrc.com
