version: '3.5'

volumes:
  mysql_data:

networks:
  web:
    external: true
  database:
    external: false

services:
  traefik:
    image: traefik:v2.4
    restart: unless-stopped
    container_name: traefik
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    env_file: mysql.env
    networks:
      - database
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: '--character-set-server=utf8 --collation-server=utf8_unicode_ci'

  main-api:
    image: openlab.ncl.ac.uk:4567/gabber/api:1.0.2-pl-beta
    restart: unless-stopped
    container_name: main-api
    env_file: gabber-main-api.env
    networks:
      - web
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mainapi.rule=Host(`api.gabber.audio`)"

  main-web:
    image: openlab.ncl.ac.uk:4567/gabber/web:0.0.3-pl
    restart: unless-stopped
    container_name: main-web
    env_file: gabber-main-web.env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mainweb.rule=Host(`gabber.audio`)"

  dev-api:
    image: openlab.ncl.ac.uk:4567/gabber/api:1.0.2-pl-beta
    restart: unless-stopped
    container_name: dev-api
    env_file: gabber-dev-api.env
    networks:
      - web
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.devapi.rule=Host(`api.dev.gabber.audio`)"

  dev-web:
    image: openlab.ncl.ac.uk:4567/gabber/web:1.0.2-beta
    restart: unless-stopped
    container_name: dev-web
    env_file: gabber-dev-web.env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.devweb.rule=Host(`dev.gabber.audio`)"

  talk-futures-api:
    image: talkfutures/api:tfl-0.0.7
    restart: unless-stopped
    container_name: talk-futures-api
    env_file: tfapi.env
    networks:
      - web
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tfapi.rule=Host(`api.tf.gabber.audio`)"

  talk-futures-web:
    image: openlab.ncl.ac.uk:4567/gabber/web:tfl-0.1.4
    restart: unless-stopped
    container_name: talk-futures-web
    env_file: tfweb.env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tfweb.rule=Host(`tf.gabber.audio`)"

  backup:
    image: schickling/mysql-backup-s3
    restart: always
    container_name: db-backup
    env_file:
      - backup.env
    environment:
      - MYSQL_HOST=mysql
      - SCHEDULE=@daily
